### ISSUE TITLE
socket.error: Socket is closed with ntc_file_copy

### ISSUE THREAD

**Issue by AnsibleAlex** [networktocode/ntc-ansible#144]
I am able to use this module to copy a small file from the ansible server to a c6500.
However, when i use this module to copy a c6k image which is 140Mb, I am getting Socket error.
Is there a way to increase the time out for scp with this module.?

Here are the tracebacks

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ck74c2/ansible_module_ntc_file_copy.py", line 262, in <module>
    main()
  File "/tmp/ansible_ck74c2/ansible_module_ntc_file_copy.py", line 254, in main
    device.close()
  File "/home/ansible/py27/python2.7/lib/python2.7/site-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py", line 60, in close
    self.native.disconnect()
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 885, in disconnect
  File "build/bdist.linux-x86_64/egg/netmiko/cisco_base_connection.py", line 52, in cleanup
  File "build/bdist.linux-x86_64/egg/netmiko/cisco_base_connection.py", line 48, in exit_config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 777, in exit_config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/cisco_base_connection.py", line 30, in check_config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 757, in check_config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 99, in write_channel
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 761, in sendall
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 715, in send
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 1081, in _send
socket.error: Socket is closed

**Comment by GGabriele** [comment]
Hi @AnsibleAlex ,
the error is not due to SCP file delivery, but to connection closing. 

Can you please verify whether the file has been delivered to the device or not?

**Comment by AnsibleAlex** [comment]
@GGabriele , Sorry for the incomplete information.
Yes the 140Mb file is copied but the playbook  declares as failed even though the job is successfully completed.  Would like to make it report as successful,

**Comment by GGabriele** [comment]
@AnsibleAlex I've just pushed a fix for this. Can you please do a git pull on `ntc-ansible` and test it again?

**Comment by AnsibleAlex** [comment]
Thanks @GGabriele . Looks like that fixed it. Pl. close this issue.

**Comment by GGabriele** [comment]
Awesome.
