### ISSUE TITLE
ntc_file_copy task fails due to module failure

### ISSUE THREAD

**Issue by lukasmuszong** [networktocode/ntc-ansible#188]
I am trying to copy an ios image onto a cisco switch and am just now getting in to ntc modules. I don't know if I am missing something in my initial system setup. The error seems to occur because the module GSSException is not available. Below is a snipped of the error message: 

```
Using module file /home/lukasm/.ansible/plugins/modules/ntc-ansible/library/ntc_file_copy.py
<10.0.111.10> ESTABLISH LOCAL CONNECTION FOR USER: lukasm
<10.0.111.10> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.0.111.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861 `" && echo ansible-tmp-1512416738.72-237111749667861="` echo /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861 `" ) && sleep 0'
<10.0.111.10> PUT /tmp/tmpb8lF4L TO /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861/ntc_file_copy.py
<10.0.111.10> EXEC /bin/sh -c 'chmod u+x /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861/ /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861/ntc_file_copy.py && sleep 0'
<10.0.111.10> EXEC /bin/sh -c '/usr/bin/python /home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861/ntc_file_copy.py; rm -rf "/home/lukasm/.ansible/tmp/ansible-tmp-1512416738.72-237111749667861/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_5Ftjb4/ansible_module_ntc_file_copy.py", line 172, in <module>
    from pyntc import ntc_device, ntc_device_by_name
  File "/usr/lib/python2.7/site-packages/pyntc/__init__.py", line 6, in <module>
    from .devices import supported_devices, DEVICE_CLASS_KEY
  File "/usr/lib/python2.7/site-packages/pyntc/devices/__init__.py", line 5, in <module>
    from .eos_device import EOSDevice, EOS_API_DEVICE_TYPE
  File "/usr/lib/python2.7/site-packages/pyntc/devices/eos_device.py", line 10, in <module>
    from .system_features.file_copy.eos_file_copy import EOSFileCopy
  File "/usr/lib/python2.7/site-packages/pyntc/devices/system_features/file_copy/eos_file_copy.py", line 1, in <module>
    import paramiko
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: 'module' object has no attribute 'GSSException'

fatal: [3850-TEST]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5Ftjb4/ansible_module_ntc_file_copy.py\", line 172, in <module>\n    from pyntc import ntc_device, ntc_device_by_name\n  File \"/usr/lib/python2.7/site-packages/pyntc/__init__.py\", line 6, in <module>\n    from .devices import supported_devices, DEVICE_CLASS_KEY\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/__init__.py\", line 5, in <module>\n    from .eos_device import EOSDevice, EOS_API_DEVICE_TYPE\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/eos_device.py\", line 10, in <module>\n    from .system_features.file_copy.eos_file_copy import EOSFileCopy\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/system_features/file_copy/eos_file_copy.py\", line 1, in <module>\n    import paramiko\n  File \"/usr/lib/python2.7/site-packages/paramiko/__init__.py\", line 22, in <module>\n    from paramiko.transport import SecurityOptions, Transport\n  File \"/usr/lib/python2.7/site-packages/paramiko/transport.py\", line 38, in <module>\n    from paramiko.auth_handler import AuthHandler\n  File \"/usr/lib/python2.7/site-packages/paramiko/auth_handler.py\", line 48, in <module>\n    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS\n  File \"/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py\", line 54, in <module>\n    GSS_EXCEPTIONS = (gssapi.GSSException,)\nAttributeError: 'module' object has no attribute 'GSSException'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0

```

**Comment by lukasmuszong** [comment]
Paramiko issue. Needed to use  ```pip install python-gssapi``` and not ```pip install gssapi```. Compare with https://github.com/paramiko/paramiko/issues/584
