### ISSUE TITLE
ntc_save_config returns IOError

### ISSUE THREAD

**Issue by lukasmuszong** [networktocode/ntc-ansible#190]
I'm trying to use the ntc_save_config for backup creation of a Cisco 3850x. I was able to run this module in the past but all of a sudden I am now receiving error messages as copied below. I have seen a couple of similar forum entries on the same error message but those were related to actual switch configurations, which I am not doing at this point as well as timeouts due to file prompts. I have ```file prompt quiet``` enabled on the switch so that I couldn't make any connection to my error and I don't know what else to try. 
Here is my module setup: 
```
 - name: Saving configs
    ntc_save_config:
      platform: cisco_ios_ssh
      provider: "{{ ios_provider }}"
      secret: "{{ enable_pass }}"
      local_file: ~/virtualenvs/ansibleTest/files/backups/RunShow{{ inventory_hostname }}.cfg
    when:
      - ansible_net_version != version
    tags: backup
```
And here is my error message I receive upon running the playbook:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_0CBbQb/ansible_module_ntc_save_config.py", line 269, in <module>
    main()
  File "/tmp/ansible_0CBbQb/ansible_module_ntc_save_config.py", line 248, in main
    remote_save_successful = device.save()
  File "/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py", line 125, in save
    self.show(command, expect=True, expect_string=expect_string)
  File "/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py", line 105, in show
    return self._send_command(command, expect=expect, expect_string=expect_string)
  File "/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py", line 75, in _send_command
    response = self.native.send_command_expect(command, expect_string=expect_string)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 985, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 967, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \[startup-config\]

fatal: [3850-TEST]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0CBbQb/ansible_module_ntc_save_config.py\", line 269, in <module>\n    main()\n  File \"/tmp/ansible_0CBbQb/ansible_module_ntc_save_config.py\", line 248, in main\n    remote_save_successful = device.save()\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py\", line 125, in save\n    self.show(command, expect=True, expect_string=expect_string)\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py\", line 105, in show\n    return self._send_command(command, expect=expect, expect_string=expect_string)\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/ios_device.py\", line 75, in _send_command\n    response = self.native.send_command_expect(command, expect_string=expect_string)\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 985, in send_command_expect\n    return self.send_command(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 967, in send_command\n    search_pattern))\nIOError: Search pattern never detected in send_command_expect: \\[startup-config\\]\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by itdependsnetworks** [comment]
Can you try the same in your ssh terminal, and then in netmiko?

**Comment by lukasmuszong** [comment]
@itdependsnetworks not sure what you suggest for me to test. If you could elaborate on this some more I would appreciate it! Thanks.

**Comment by jmcgill298** [comment]
@lukasmuszong the issue you are having may be fixed if you update pyntc. That method that is generating the error was patched on Dec 15, 2016. Can you update and let us know if that fixes it?

**Comment by jmcgill298** [comment]
@lukasmuszong any chance on testing with an updated version?

**Comment by jmcgill298** [comment]
Believed to be fixed
