### ISSUE TITLE
ntc_install_os: Problem when device is in INSTALL mode and doesnt use boot statements

### ISSUE THREAD

**Issue by hazelfire5** [networktocode/ntc-ansible#195]
Hello,
I am running into an issue where our Cisco IOS Switches are in `INSTALL` Mode and do not use boot statements to install the OS like `BUNDLE` Mode. Instead, the command used is `software install file flash:x.x.x.bin`.
```
---
- name: Cisco IOS Upgrade
  hosts: lab_nas
  connection: local
  gather_facts: no


  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      platform: "{{ plat_form_ssh }}"
      connection: ssh

  tasks:
  - name: install os
    register: install_os
    ntc_install_os:
      provider: "{{ cli }}"
      system_image_file: "{{ image_file }}"
  - debug: var=install_os
```
I am getting this error that seems to stem from `get_boot_options` not getting the boot options.
```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gn/T/ansible_nnZD9u/ansible_module_ntc_install_os.py", line 290, in <module>
    main()
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gn/T/ansible_nnZD9u/ansible_module_ntc_install_os.py", line 249, in main
    current_boot_options = device.get_boot_options()
  File "/Library/Python/2.7/site-packages/pyntc/devices/ios_device.py", line 198, in get_boot_options
    boot_path = re.search(boot_path_regex, show_boot_out).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

fatal: [10.1.1.2]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gn/T/ansible_nnZD9u/ansible_module_ntc_install_os.py\", line 290, in <module>\n    main()\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gn/T/ansible_nnZD9u/ansible_module_ntc_install_os.py\", line 249, in main\n    current_boot_options = device.get_boot_options()\n  File \"/Library/Python/2.7/site-packages/pyntc/devices/ios_device.py\", line 198, in get_boot_options\n    boot_path = re.search(boot_path_regex, show_boot_out).group(1)\nAttributeError: 'NoneType' object has no attribute 'group'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

I ran `show run | i boot` to gather the boot options and I can see that in `INSTALL` mode the running-config does not contain the binary file statement.
```
10.1.1.2#show run | i boot
boot-start-marker
boot system switch all flash:packages.conf
boot-end-marker
```

Hopefully I am making sense... Or I am just tired... but either way, is there anything that can be done to fix this?

**Comment by Noname2244** [comment]
There's a big difference between INSTALL and BUNDLE , BUNDLE is the old way , point boot to a new image. INSTALL "installs" the different packages. 

INSTALL mode is not to my knowledge supported.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
