### ISSUE TITLE
F5 errors

### ISSUE THREAD

**Issue by hrv231** [networktocode/ntc-ansible#253]
Hello,

I have tried already with two versions of linux and both give me the same error:
```

Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyntc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/pyntc/__init__.py", line 6, in <module>
    from .devices import supported_devices
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/pyntc/devices/__init__.py", line 10, in <module>
    from .f5_device import F5Device
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/pyntc/devices/f5_device.py", line 11, in <module>
    from f5.bigip import ManagementRoot
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/f5/bigip/__init__.py", line 36, in <module>
    from f5.bigip.tm.auth import Auth as TmAuth
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/f5/bigip/tm/__init__.py", line 27, in <module>
    from f5.bigip.tm.net import Net
  File "/home/debian/environments/ntc-ansible/lib/python3.7/site-packages/f5/bigip/tm/net/__init__.py", line 31, in <module>
    from f5.bigip.tm.net.arp import Arps
ImportError: cannot import name 'Arps' from 'arp' (unknown location)
```

Can someone please tell me what am I doing wrong?
because of this error, I can't use the ntc_file_copy.

Thank you!

**Comment by FragmentedPacket** [comment]
This looks to do with some namespacing changes in Python 3.7 If you use 3.6, it should work for you.

**Comment by hrv231** [comment]
Thank you for the input.

I tested it on python 3.6 and still the same error:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyntc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyntc-0.0.9-py3.6.egg/pyntc/__init__.py", line 6, in <module>
    from .devices import supported_devices
  File "/usr/local/lib/python3.6/dist-packages/pyntc-0.0.9-py3.6.egg/pyntc/devices/__init__.py", line 10, in <module>
    from .f5_device import F5Device
  File "/usr/local/lib/python3.6/dist-packages/pyntc-0.0.9-py3.6.egg/pyntc/devices/f5_device.py", line 11, in <module>
    from f5.bigip import ManagementRoot
  File "/usr/local/lib/python3.6/dist-packages/f5_sdk-3.0.21-py3.6.egg/f5/bigip/__init__.py", line 36, in <module>
    from f5.bigip.tm.auth import Auth as TmAuth
  File "/usr/local/lib/python3.6/dist-packages/f5_sdk-3.0.21-py3.6.egg/f5/bigip/tm/__init__.py", line 27, in <module>
    from f5.bigip.tm.net import Net
  File "/usr/local/lib/python3.6/dist-packages/f5_sdk-3.0.21-py3.6.egg/f5/bigip/tm/net/__init__.py", line 31, in <module>
    from f5.bigip.tm.net.arp import Arps
ImportError: cannot import name 'Arps'
>>>
```

Any other suggestion?

**Comment by FragmentedPacket** [comment]
Can you do `pip freeze` and post the output here? I'm only able to reproduce on Python 3.7

**Comment by hrv231** [comment]
Thank you for helping on this.
I must say, this is really weird, because today I spin up a VM just to test this.
I installed Debian, and then start installing python3, python3-venv and the other python3.
No python2 on the VM.
Then I use the venv to install ansible and all the dependencies for NTC-Ansible, and I'm still getting the same error, the worst of all is that I don't get any error when installing all my packages using pip.
I think that something might be wrong with the f5 and f5-icontrol, because I tried to use the ntc_file_copy and it gives me the same error.

Below is the pip freeze:
```
(test) user1@NETMAN:~$ pip freeze
ansible==2.8.5
asn1crypto==1.0.1
attrs==19.2.0
bcrypt==3.1.7
bigsuds==1.0.6
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
coverage==4.5.4
cryptography==2.7
f5-icontrol-rest==1.3.13
f5-sdk==3.0.21
future==0.18.0
idna==2.8
importlib-metadata==0.23
Jinja2==2.10.3
jsonschema==3.1.1
junos-eznc==2.3.0
lxml==4.4.1
MarkupSafe==1.1.1
mock==3.0.5
more-itertools==7.2.0
ncclient==0.6.6
netaddr==0.7.19
netmiko==2.4.2
paramiko==2.6.0
pkg-resources==0.0.0
pycparser==2.19
pyeapi==0.8.2
PyNaCl==1.3.0
pyntc==0.0.9
pynxos==0.0.5
pyparsing==2.4.2
pyrsistent==0.15.4
pyserial==3.4
PyYAML==5.1.2
requests==2.22.0
scp==0.13.2
six==1.12.0
suds-jurko==0.6
terminal==0.4.0
textfsm==1.1.0
transitions==0.7.1
urllib3==1.25.6
yamlordereddictloader==0.4.0
zipp==0.6.0
(test) user1@NETMAN:~$              
```

Thanks.

**Comment by hrv231** [comment]
Another update.
I decided to run WSL on a laptop and installed Ubuntu 16.04 LTS, as soon as I did that, Ubuntu comes with python 3.5.2
I installed ansible using pip3 and then installed pyntc using pip3.
After that I ran python3 and ran import pyntc.

Same error, I'm pretty sure Im doing everything by the book, I don't know what is broken, but this must be happening to everybody now.

How exactly do you guys make this work??

```
(test) user1@NETMAN:~$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyntc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/test/lib/python3.5/site-packages/pyntc/__init__.py", line 6, in <module>
    from .devices import supported_devices
  File "/home/user1/test/lib/python3.5/site-packages/pyntc/devices/__init__.py", line 10, in <module>
    from .f5_device import F5Device
  File "/home/user1/test/lib/python3.5/site-packages/pyntc/devices/f5_device.py", line 11, in <module>
    from f5.bigip import ManagementRoot
  File "/home/user1/test/lib/python3.5/site-packages/f5/bigip/__init__.py", line 36, in <module>
    from f5.bigip.tm.auth import Auth as TmAuth
  File "/home/user1/test/lib/python3.5/site-packages/f5/bigip/tm/__init__.py", line 27, in <module>
    from f5.bigip.tm.net import Net
  File "/home/user1/test/lib/python3.5/site-packages/f5/bigip/tm/net/__init__.py", line 31, in <module>
    from f5.bigip.tm.net.arp import Arps
ImportError: cannot import name 'Arps'
>>>
```

**Comment by FragmentedPacket** [comment]
Sorry about the delay in responding. I was testing on an existing virtualenv that had junos-eznc==2.2.1 and it was working.

It appears **junos-eznc** has broken the functionality so at this point, if you install junos-eznc==2.2.1 it should work.

We should look into pinning the versions within setup until we look into this further.

**Comment by hrv231** [comment]
You sir are the best!
Thank you very much for helping on this, finally I can start using ntc-ansible.

Thanks for your time.
