### ISSUE TITLE
setup.py: "ImportError No module named pathlib"

### ISSUE THREAD

**Issue by sumkincpp** [networktocode/ntc-ansible#255]
It looks like pathlib now is a missing dependency for Python2

During module installation -
```bash
$ pip install --upgrade ntc-ansible
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting ntc-ansible
  Downloading https://files.pythonhosted.org/packages/bf/a3/62c21dadd1a4063ccfe292b65e6174788d4eaeb7f5afc63632f3eb22bce0/ntc-ansible-0.9.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/awx/awx-app/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-E1WUmq/ntc-ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-E1WUmq/ntc-ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-E1WUmq/ntc-ansible/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-E1WUmq/ntc-ansible/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

After installing pathlib
```
# pip install --upgrade ntc-ansible
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting ntc-ansible
  Using cached https://files.pythonhosted.org/packages/bf/a3/62c21dadd1a4063ccfe292b65e6174788d4eaeb7f5afc63632f3eb22bce0/ntc-ansible-0.9.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/awx/awx-app/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UTlKkl/ntc-ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-UTlKkl/ntc-ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-UTlKkl/ntc-ansible/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UTlKkl/ntc-ansible/setup.py", line 6, in <module>
        README = (CWD / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jmcgill298** [comment]
Can you try with v0.9.2?

**Comment by sumkincpp** [comment]
Thanks, everything works again!

Could you please also check #246, #247?

**Comment by jmcgill298** [comment]
Thanks for reporting and confirming the fix
