### ISSUE TITLE
pyntc cannot import name ntc_device error

### ISSUE THREAD

**Issue by Mohamedelmrakby** [networktocode/ntc-ansible#260]
i have tried to install pyntc but i get the below error, i'm usine python 2.7 and netmiko 2.4.2

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import pyntc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyntc\__init__.py", line 6, in <module>
    from .devices import supported_devices
  File "C:\Python27\lib\site-packages\pyntc\devices\__init__.py", line 7, in <module>
    from .ios_device import IOSDevice
  File "C:\Python27\lib\site-packages\pyntc\devices\ios_device.py", line 9, in <module>
    from pyntc.templates import get_structured_data
  File "C:\Python27\lib\site-packages\pyntc\templates\__init__.py", line 2, in <module>
    import textfsm
  File "C:\Python27\lib\site-packages\textfsm\__init__.py", line 11, in <module>
    from textfsm.parser import *
ImportError: No module named parser
>>>

================= RESTART: C:\Users\EOMEHLM\Desktop\pyntc.py =================

Traceback (most recent call last):
  File "C:\Users\EOMEHLM\Desktop\pyntc.py", line 2, in <module>
    from pyntc import ntc_device as NTC
  File "C:\Users\EOMEHLM\Desktop\pyntc.py", line 2, in <module>
    from pyntc import ntc_device as NTC
ImportError: cannot import name ntc_device
>>>

**Comment by jmcgill298** [comment]
what version of textfsm do you have installed?

**Comment by Mohamedelmrakby** [comment]
version 1.1.0

**Comment by jmcgill298** [comment]
something seems to be off with your installation of textfsm as the Exception is raised from that library:
```
File "C:\Python27\lib\site-packages\textfsm_init_.py", line 11, in
from textfsm.parser import *
ImportError: No module named parser
```

I tested with linux and py3 and it worked fine:
```
>>> from textfsm.parser import *
>>> import textfsm
>>> textfsm.__version__
'1.1.0'
>>>
```

Are you able to test on Linux?
